apiVersion: fission.io/v1
kind: Package
metadata:
  name: web-pkg
  namespace: default
spec:
  deployment:
    url: archive://web-pkg-zip
  buildcmd: "build"
  environment:
    name: python
    namespace: default
status:
  buildstatus: succeeded

---
kind: ArchiveUploadSpec
name: web-pkg-zip
include:
  - "*"
