apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: kc 
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 2
      MinScale: 1
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: java
    namespace: default
  package:
    functionName: io.fission.kafka.IotConsumer
    packageref:
      name: iot-kafka-consumer-1-0-0-jar-with-dependencies-jar-ywpb
      namespace: default
  resources: {}
  secrets: null
